### ISSUE TITLE
Investigate if using the events for linked issues work properly

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-backports#18] opened 2020-07-27 09:33 UTC
Case I'm worried about: we just reference a PR in an issue with "see #pr-id" and we end up closing the issue while the PR is not fixing it.

Note that it is not theoretical and it happens from time to time (I know because I usually track the fixed issues manually by scrolling through the events).

The other option will be to parse the description of the PR.

**Comment by gastaldi** [comment] 2020-07-27 19:55
I just tested and I can confirm that the current solution ignores "See #PR-ID" comments. Closing now

**Comment by gastaldi** [comment] 2020-07-27 20:53
I'll perform more tests. Looks like there are some cases where the issue is not linked in the PR

**Comment by gsmet** [comment] 2020-07-29 11:15
Yeah, that's what people mentioned in the link you provided the other day.

I think we should just implement our own parsing logic and look for something along the lines of `(?:fix(?:es|ed)?|resolve[sd]?|close[sd]?)\s+(?:#([0-9]+))\s+`. We could even support multiple issues after the verb.

Would it work for you?

**Comment by gsmet** [comment] 2020-07-29 11:20
We might also need to catch things when people use the full URL as it's supported by GH.

**Comment by gsmet** [comment] 2020-07-29 11:32
Note: we also need to take into account `Fix:` with a colon.

**Comment by gsmet** [comment] 2020-07-29 12:49
I haven't covered everything but you have a good set of examples here: https://github.com/gsmet/backports-test/pull/2 .

The gist of it is that we need to support fix/fixes/fixed/resolve/resolves/resolved/close/closes/closed with and without a colon and spaces before the issue number. The issue number could be `#000` or `https://github.com/<repository>/issues/12`.

Be careful, visually, GH replaces the URL by the hash version. In the example `#12` is a link.

**Comment by gsmet** [comment] 2020-07-29 12:52
@gastaldi I updated my regexp above, it shouldn't be that far from what we want.

**Comment by gsmet** [comment] 2020-07-29 13:13
(and debug it ;))

**Comment by gastaldi** [comment] 2020-07-29 13:17
Hm, your regex is missing a `)`. I'll provide a PR with this extraction mechanism in place and then we can simply improve it

**Closed** 2020-07-29 18:15 UTC
Labels: bug
